[sources.syslog_logs]
type = "demo_logs"
format = "syslog"

[sources.apache_common_logs]
type = "demo_logs"
format = "apache_common"

[sources.apache_error_logs]
type = "demo_logs"
format = "apache_error"

[sources.json_logs]
type = "demo_logs"
format = "json"

# Parse Syslog logs
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.parse_logs]
type = "remap"
inputs = ["syslog_logs"]
source = '''
. = parse_syslog!(string!(.message))
'''

# Export data to Uptrace.
[sinks.uptrace]
type = "http"
method = "post"
inputs = ["parse_logs", "apache_common_logs", "apache_error_logs", "json_logs"]
encoding.codec = "json"
framing.method = "newline_delimited"
compression = "gzip"
uri = "https://uptrace:443/api/v1/vector/logs"
#uri = "https://api.uptrace.dev/api/v1/vector/logs"
tls.verify_certificate = false
request.headers.uptrace-dsn = "https://project1_secret@localhost:14318?grpc=14317"
